_BASE_: "mask_rcnn_X_101_32x8d_FPN_3x.yaml"
MODEL:
  BACKBONE:
    FREEZE_AT: 2
  WEIGHTS: "detectron2://ImageNetPretrained/FAIR/X-101-32x8d.pkl"
  PIXEL_MEAN: [103.530, 116.280, 123.675]
  PIXEL_STD: [57.375, 57.120, 58.395]
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 512
    NUM_CLASSES: 20
DATALOADER:
  NUM_WORKERS: 8
DATASETS:
  TRAIN: ("training", )
  TEST: ("validation",)
TEST:
  EVAL_PERIOD: 0
INPUT:
  MIN_SIZE_TRAIN: (800, )
  MIN_SIZE_TRAIN_SAMPLING: "choice"
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1333
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.004
  GAMMA: 0.5
  STEPS: () # (210000, 250000)
  MAX_ITER: 2200000
  IMS_LEN: 100000
  EPOCHS: 10
  OPTIM: "SGD"
  MONITOR: "total_val_loss"
  CHECKPOINT_PERIOD: 5 # epochs
  EARLY_STOPPING:
    ENABLED: False
    PATIENCE: 0
OUTPUT_DIR: './mask_rcnn_resneXt'